"""Dashboard backend.

Reads the artifacts the gateway already produces - the audit log, the taint
records, the manifest findings - and serves them over a small JSON API. It adds
no security logic of its own; it is a viewer. That separation matters: the
dashboard can be wrong or absent without affecting whether the gateway blocks
anything.

    python -m dashboard.app --db audit.db
    python -m dashboard.app --demo        # runs s04 live, then serves it

The dashboard renders attacker-controlled strings (tool arguments, injected
text). Those are escaped by the frontend and never interpreted as markup - a
security tool that XSSes itself on the payloads it captured would be a poor
advertisement. The API returns raw JSON; escaping is the client's job.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from fastapi import FastAPI, HTTPException
from fastapi.responses import HTMLResponse
from fastapi.staticfiles import StaticFiles

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from gateway.audit.log import AuditLog

app = FastAPI(title="MCP Security Gateway")

# Set by main(); the API reads whichever audit db was requested.
DB_PATH = {"path": str(ROOT / "audit.db")}
STATIC = Path(__file__).parent / "static"


def _log() -> AuditLog:
    path = DB_PATH["path"]
    if not Path(path).exists():
        raise HTTPException(404, f"no audit db at {path}")
    return AuditLog(path)


@app.get("/api/sessions")
def sessions() -> list[dict]:
    """Every session in the log, newest first, with a one-line summary."""
    log = _log()
    seen: dict[str, dict] = {}
    for e in log.events():
        sid = e["session_id"]
        s = seen.setdefault(sid, {
            "session_id": sid, "started": e["ts"], "calls": 0,
            "denied": 0, "taint_labels": 0, "manifest_flags": 0, "server": None,
        })
        if e["kind"] == "session_start":
            try:
                s["server"] = json.loads(e["payload"]).get("server_cmd", [None])[-1]
            except Exception:
                pass
        if e["method"] == "tools/call" and e["direction"] == "client_to_server":
            s["calls"] += 1
            if e["verdict"] in ("deny", "require_approval"):
                s["denied"] += 1
        if e["kind"] == "taint":
            s["taint_labels"] += 1
        if e["kind"] == "manifest":
            try:
                s["manifest_flags"] += len(json.loads(e["payload"]).get("findings", []))
            except Exception:
                pass
    log.close()
    return sorted(seen.values(), key=lambda s: s["started"], reverse=True)


@app.get("/api/session/{session_id}")
def session(session_id: str) -> dict:
    """The full timeline of one session: every tool call with its verdict, the
    rule that fired, taint labels applied, and manifest findings."""
    log = _log()
    events = list(log.events(session_id))
    log.close()
    if not events:
        raise HTTPException(404, f"no session {session_id}")

    calls, taint, manifest = [], [], []
    for e in events:
        payload = json.loads(e["payload"])
        if e["method"] == "tools/call" and e["direction"] == "client_to_server":
            params = payload.get("params", {})
            calls.append({
                "seq": e["seq"],
                "tool": params.get("name"),
                "arguments": params.get("arguments", {}),
                "verdict": e["verdict"],
                "rule": e["rule_id"],
                "latency_ms": e["latency_ms"],
            })
        elif e["kind"] == "taint":
            taint.append({"seq": e["seq"], **payload})
        elif e["kind"] == "manifest":
            manifest.append({"seq": e["seq"], **payload})

    return {
        "session_id": session_id,
        "calls": calls,
        "taint": taint,
        "manifest": manifest,
        "verify": _verify(session_id),
    }


def _verify(session_id: str) -> dict:
    log = _log()
    result = log.verify()
    log.close()
    return {"ok": result.ok, "checked": result.checked, "broken_at": result.broken_at}


@app.get("/api/benchmark")
def benchmark() -> dict:
    """The saved benchmark results, if present. Generated by harness.bench
    --json; the dashboard does not run the benchmark itself."""
    path = ROOT / "docs" / "benchmark.json"
    sweep = ROOT / "docs" / "sweep.json"
    return {
        "benchmark": json.loads(path.read_text()) if path.exists() else None,
        "sweep": json.loads(sweep.read_text()) if sweep.exists() else None,
    }


@app.get("/", response_class=HTMLResponse)
def index() -> str:
    return (STATIC / "index.html").read_text(encoding="utf-8")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--db", default=str(ROOT / "audit.db"))
    ap.add_argument("--host", default="127.0.0.1")
    ap.add_argument("--port", type=int, default=8000)
    ap.add_argument("--demo", action="store_true",
                    help="run s01 and s04 through the gateway first, then serve")
    args = ap.parse_args()

    if args.demo:
        args.db = _build_demo()

    DB_PATH["path"] = args.db
    app.mount("/static", StaticFiles(directory=STATIC), name="static")

    import uvicorn
    print(f"\n  dashboard: http://{args.host}:{args.port}\n  audit db:  {args.db}\n")
    uvicorn.run(app, host=args.host, port=args.port, log_level="warning")
    return 0


def _build_demo() -> str:
    """Run the flagship scenarios through the full gateway into one audit db, so
    the dashboard has something real to show on first open."""
    import tempfile
    import harness.run as R

    db = str(Path(tempfile.mkdtemp(prefix="mcpgw-demo-")) / "audit.db")
    # Patch the runner to keep its audit db instead of deleting it, and point
    # it at our fixed path.
    orig_rmtree = R.shutil.rmtree
    R.shutil.rmtree = lambda *a, **k: None
    orig_mkdtemp = R.tempfile.mkdtemp
    workdir = Path(db).parent
    R.tempfile.mkdtemp = lambda **kw: str(workdir)
    try:
        for scenario in ("s01_direct_injection", "s04_confused_deputy"):
            R.run(ROOT / "scenarios" / scenario, "full")
    finally:
        R.shutil.rmtree = orig_rmtree
        R.tempfile.mkdtemp = orig_mkdtemp
    return db


if __name__ == "__main__":
    raise SystemExit(main())
